// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241230132524_AddDiaryEntrySeedData")]
    partial class AddDiaryEntrySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "went shoping with Joe!",
                            Created = new DateTime(2024, 12, 30, 21, 25, 23, 705, DateTimeKind.Local).AddTicks(6570),
                            Title = "went shoping"
                        },
                        new
                        {
                            Id = 2,
                            Content = "went eatting with Joe!",
                            Created = new DateTime(2024, 12, 30, 21, 25, 23, 705, DateTimeKind.Local).AddTicks(6696),
                            Title = "went eatting"
                        },
                        new
                        {
                            Id = 3,
                            Content = "went hiking with Joe!",
                            Created = new DateTime(2024, 12, 30, 21, 25, 23, 705, DateTimeKind.Local).AddTicks(6697),
                            Title = "went hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
